### ISSUE TITLE
✅ [공통] 게시물 업로드 모달

### ISSUE THREAD

**Issue by djswns7** [mighty-paws/Petstagram#24]
## 작업 사항
> 작업 사항(구현할 내용)을 입력해주세요.
완료된 작업 사항은 제목에 완료한 이슈 번호를 입력해주세요.

## Todo
- [ ] 게시물 업로드 모달 기본구조 생성
- [ ] 모달 active 상태변수 생성 및 관리
- [ ] 모달 css 적용
- [ ] 반응형 스타일 적용
- [ ] 이미지 파일 업로드 기능 추가
- [ ] 이미지 다중 삽입 시 스와이퍼 슬라이더 추가
- [ ] 이미지 설명(문구입력) 입력 기능 추가 ( 옵션: 글자 수 표기 / 이모지 추가 ) 
- [ ] 접근성 대체 텍스트 입력란 추가

## 기타
> - [ ] 이미지 편집 기능(자르기) 추가 (미정)
