### ISSUE TITLE
✅ [메인] 팔로우 추천 컴포넌트 마크업

### ISSUE THREAD

**Issue by to06109** [mighty-paws/Petstagram#27]
## 작업 사항
- [x] 팔로우 추천 컴포넌트 마크업

## Todo
- [x] 팔로우 목록 컴포넌트 마크업
- [x] 팔로우 추천 컴포넌트 마크업
