### ISSUE TITLE
✅ [메인] 게시물 데이터 불러와서 화면에 렌더링

### ISSUE THREAD

**Issue by to06109** [mighty-paws/Petstagram#31]
## 작업 사항
> 게시물 데이터 불러와서 화면에 렌더링

## Todo
- [x] 메인 무한스크롤 구현
- [x] firebase의 posts 객체 불러와서 렌더링
- [x] 로그인한 user의 데이터를 redux로 상태관리
- [x] 사용자가 follow한 사람들의 post를 최신순으로 불러와서 렌더링(createAsyncThunk 이용)
- [x] post게시한 유저의 usersData 불러와서 렌더링
-> 프로필 이미지, 이메일, 이미지, 콘텐츠
-> 좋아요 한 사람 수에 따라 'OOO 외 몇 명이 좋아합니다' 구현
-> 포스트 한 기간 계산해서 'O일 전' 구현
- [x] 댓글 데이터 렌더링
-> comment 객체에 email 추가

![image](https://user-images.githubusercontent.com/69625013/235533915-0764cca2-7bd9-424e-9240-4ad37682c930.png)
