### ISSUE TITLE
✅ [2023.05.10] token 추가

### ISSUE THREAD

**Issue by to06109** [mighty-paws/Petstagram#50]
## 작업 사항
> token 추가

## Todo
- [x] tokens.js 파일 추가
- [x] 색상 문자열만으로 색상 가져올 수 있는 util함수 구현
- [x] 사용 예시 제공

색상 변화하는 것 확인했습니다!
`<MenuSection bgColor={getColor('primary Yellow/primary yellow-100')}>
        메뉴바
      </MenuSection>`
<img src='https://github.com/mighty-paws/Petstagram/assets/69625013/18c58cd2-ca39-464c-a087-a72a081ec01e' width='200px' />
`<MenuSection bgColor={getColor('primary color')}>메뉴바</MenuSection>`
<img src='https://github.com/mighty-paws/Petstagram/assets/69625013/1361e37c-0928-45a6-be56-72d755aad8f9' width='200px' />

## 기타
> 필요한 경우 작성해주세요.
