### ISSUE TITLE
✅ [메인] swiper 컴포넌트 제작

### ISSUE THREAD

**Issue by to06109** [mighty-paws/Petstagram#7]
## 작업 사항
- [x] 이미지 배열을 받아 swiper 컴포넌트 제작

## Todo
- [x] 이미지 배열을 props로 받게 제작
- [x] 키보드 접근성 지키기
